#versão docker-compose
version: '3.8'


services:
  app:
    build: . # a localizaçao onde ta aplicando 
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    restart: unless-stopped



## Docker-file mysql - node 
### https://www.youtube.com/watch?v=4-sKL_E1I0I

#     version: "3.8"


# services:
#     mysqldb:
#         image: mysql:5.7
#         container_name: todosimple-mysql
#         restart: unless-stopped
#         env_file: ./.env
#         environment:
#             - MYSQL_ROOT_PASSWORD=$MYSQL_PASSWORD
#             - MYSQL_DATABASE=$MYSQL_DATABASE
#             - MYSQL_TCP_PORT=$MYSQL_DOCKER_PORT
#         ports:
#             - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
#         expose:
#             - $MYSQL_DOCKER_PORT
#         healthcheck:
#             test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
#             timeout: 5s
#             retries: 10
#     app:
#         depends_on:
#             mysqldb:
#                 condition: service_healthy
#         build:
#             context: ./
#             dockerfile: Dockerfile
#         working_dir: /usr/src/todosimple
#         container_name: todosimple-api
#         restart: unless-stopped
#         env_file: ./.env
#         environment:
#             - MYSQL_HOST=mysqldb
#             - MYSQL_LOCAL_PORT=$MYSQL_DOCKER_PORT
#             - MYSQL_DATABASE=$MYSQL_DATABASE
#             - MYSQL_USERNAME=$MYSQL_USERNAME
#             - MYSQL_PASSWORD=$MYSQL_PASSWORD
#         ports:
#             - $NODE_LOCAL_PORT:$NODE_LOCAL_PORT
#         stdin_open: true
#         tty: true